name: Fetch All Data
on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess-magiceden.ts
      - ./postprocess-solanart.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2

      - name: saibagang - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22saiba_gang%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: saibagang__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: saibagang - Fetch Solanart data
        uses: githubocto/flat@v3
        with:
          http_url: https://qzlsklfacc.medianetwork.cloud/nft_for_sale?collection=saibagang
          downloaded_filename: saibagang__solanart.json
          postprocess: ./postprocess-solanart.ts

      - name: towerdao - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22the_tower%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: towerdao__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: towerdao - Fetch Solanart data
        uses: githubocto/flat@v3
        with:
          http_url: https://qzlsklfacc.medianetwork.cloud/nft_for_sale?collection=thetower
          downloaded_filename: towerdao__solanart.json
          postprocess: ./postprocess-solanart.ts

      - name: towerdao - Fetch Alpha Art data
        uses: githubocto/flat@v3
        with:
          http_url: https://apis.alpha.art/api/v1/collection
          downloaded_filename: towerdao__alphaart.json
          axios_config: .github/alpha_axios_configs/towerdao.json
          postprocess: ./postprocess-alphaart.ts

      - name: gloompunkclub - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22gloom_punk_club%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: gloompunkclub__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: gloompunkclub - Fetch Solanart data
        uses: githubocto/flat@v3
        with:
          http_url: https://qzlsklfacc.medianetwork.cloud/nft_for_sale?collection=gloompunk
          downloaded_filename: gloompunkclub__solanart.json
          postprocess: ./postprocess-solanart.ts

      - name: gloompunkclub - Fetch Alpha Art data
        uses: githubocto/flat@v3
        with:
          http_url: https://apis.alpha.art/api/v1/collection
          downloaded_filename: gloompunkclub__alphaart.json
          axios_config: .github/alpha_axios_configs/gloompunkclub.json
          postprocess: ./postprocess-alphaart.ts

      - name: crypto_cultists - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22crypto_cultist%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: crypto_cultists__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: solsunsets - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22solsunsets%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: solsunsets__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: solsunsets - Fetch Alpha Art data
        uses: githubocto/flat@v3
        with:
          http_url: https://apis.alpha.art/api/v1/collection
          downloaded_filename: solsunsets__alphaart.json
          axios_config: .github/alpha_axios_configs/solsunsets.json
          postprocess: ./postprocess-alphaart.ts

      - name: flamingo_party - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22flamingo_party%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: flamingo_party__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: flamingo_party - Fetch Alpha Art data
        uses: githubocto/flat@v3
        with:
          http_url: https://apis.alpha.art/api/v1/collection
          downloaded_filename: flamingo_party__alphaart.json
          axios_config: .github/alpha_axios_configs/flamingo_party.json
          postprocess: ./postprocess-alphaart.ts

      - name: careless_cats - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22careless_cats%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: careless_cats__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: careless_cats - Fetch Alpha Art data
        uses: githubocto/flat@v3
        with:
          http_url: https://apis.alpha.art/api/v1/collection
          downloaded_filename: careless_cats__alphaart.json
          axios_config: .github/alpha_axios_configs/careless_cats.json
          postprocess: ./postprocess-alphaart.ts

      - name: pixel_creatures - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22pixel_creatures%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: pixel_creatures__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: solsocks - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22solsocks%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: solsocks__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: solsocks - Fetch Alpha Art data
        uses: githubocto/flat@v3
        with:
          http_url: https://apis.alpha.art/api/v1/collection
          downloaded_filename: solsocks__alphaart.json
          axios_config: .github/alpha_axios_configs/solsocks.json
          postprocess: ./postprocess-alphaart.ts

      - name: solsteads - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22solsteads_surreal_estate%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: solsteads__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: solsteads - Fetch Solanart data
        uses: githubocto/flat@v3
        with:
          http_url: https://qzlsklfacc.medianetwork.cloud/nft_for_sale?collection=solsteads
          downloaded_filename: solsteads__solanart.json
          postprocess: ./postprocess-solanart.ts

      - name: solsteads - Fetch Alpha Art data
        uses: githubocto/flat@v3
        with:
          http_url: https://apis.alpha.art/api/v1/collection
          downloaded_filename: solsteads__alphaart.json
          axios_config: .github/alpha_axios_configs/solsteads.json
          postprocess: ./postprocess-alphaart.ts

      - name: meerkatmillionaires - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22meerkat_millionaires_country_club%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: meerkatmillionaires__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: meerkatmillionaires - Fetch Solanart data
        uses: githubocto/flat@v3
        with:
          http_url: https://qzlsklfacc.medianetwork.cloud/nft_for_sale?collection=meerkatmillionairescc
          downloaded_filename: meerkatmillionaires__solanart.json
          postprocess: ./postprocess-solanart.ts

      - name: galacticgeckos - Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22galactic_geckos%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: galacticgeckos__magiceden.json
          postprocess: ./postprocess-magiceden.ts

      - name: galacticgeckos - Fetch Solanart data
        uses: githubocto/flat@v3
        with:
          http_url: https://qzlsklfacc.medianetwork.cloud/nft_for_sale?collection=galacticgeckospacegarage
          downloaded_filename: galacticgeckos__solanart.json
          postprocess: ./postprocess-solanart.ts
