name: saibagang
on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/saibagang.yml
      - ./postprocess-magiceden.ts
      - ./postprocess-solanart.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch Magic Eden data
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.io/rpc/getListedNFTsByQuery?q=%7B%22%24match%22%3A%7B%22collectionSymbol%22%3A%22saiba_gang%22%7D%2C%22%24sort%22%3A%7B%22takerAmount%22%3A1%2C%22createdAt%22%3A-1%7D%7D
          downloaded_filename: saibagang__magiceden.json
          postprocess: ./postprocess-magiceden.ts
      - name: Fetch Solanart data
        uses: githubocto/flat@v3
        with:
          http_url: https://qzlsklfacc.medianetwork.cloud/nft_for_sale?collection=saibagang
          downloaded_filename: saibagang__solanart.json
          postprocess: ./postprocess-solanart.ts
